<?php

/**
 * @file
 * Home page.
 */

/**
 * Implements hook_menu().
 */
function home_menu() {

  $rows = array();

  $rows['home'] = array(
    'title' => 'Home',
    'page callback' => 'home_content',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dohome.inc'
  );

  return $rows;
}

/**
 * Implements hook_theme().
 */
function home_theme($existing, $type, $theme, $path) {

  $thePath = drupal_get_path('module', 'home') . '/templates';

  return array(
    'template_home' => array(
      'template' => 'home',
      'path' => $thePath,
    ),
  );
}


